# Generated by Django 5.1.7 on 2025-03-28 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventClass',
            fields=[
                ('event_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_title', models.CharField(max_length=100)),
                ('class_description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('event_day_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_date', models.DateField()),
                ('event_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('enrolment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrol_status', to=settings.AUTH_USER_MODEL)),
                ('class_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='diary.eventclass')),
            ],
        ),
        migrations.AddField(
            model_name='eventclass',
            name='class_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_classes', to='diary.eventday'),
        ),
    ]
