# Generated by Django 5.1.7 on 2025-03-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='class_title',
        ),
        migrations.RemoveField(
            model_name='enrolment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='eventclass',
            name='class_date',
        ),
        migrations.RenameField(
            model_name='eventday',
            old_name='event_day_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='eventday',
            name='event_title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='eventday',
            constraint=models.UniqueConstraint(condition=models.Q(('event_title__iexact', models.F('event_title'))), fields=('event_title',), name='unique_event_title_case_insensitive'),
        ),
        migrations.DeleteModel(
            name='Enrolment',
        ),
        migrations.DeleteModel(
            name='EventClass',
        ),
    ]
