# Generated by Django 5.1.7 on 2025-04-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_enrolment_class_title_remove_enrolment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventday',
            name='event_description',
            field=models.TextField(default='Details'),
            preserve_default=False,
        ),
    ]
