# Generated by Django 5.1.7 on 2025-04-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_eventday_event_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventday',
            name='unique_event_title_case_insensitive',
        ),
        migrations.RenameField(
            model_name='eventday',
            old_name='event_description',
            new_name='day_description',
        ),
        migrations.RenameField(
            model_name='eventday',
            old_name='event_title',
            new_name='day_title',
        ),
        migrations.AddConstraint(
            model_name='eventday',
            constraint=models.UniqueConstraint(condition=models.Q(('day_title__iexact', models.F('day_title'))), fields=('day_title',), name='unique_event_title_case_insensitive'),
        ),
    ]
