# Generated by Django 5.1.7 on 2025-04-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_remove_eventday_unique_event_title_case_insensitive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventday',
            old_name='class_date',
            new_name='day_date',
        ),
    ]
