# Generated by Django 5.1.7 on 2025-04-02 13:25

from django.db import migrations, models


# Issue #112: CloudinaryField was replaced by ImageField, and the
# cloudinary package removed. Historical migrations only have to
# reproduce the schema, and CloudinaryField is a varchar(255), so
# CharField stands in for it exactly. Do not reintroduce the import.
class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photograph',
            field=models.CharField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
