# Generated by Django 5.2.1 on 2026-08-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_userprofile_photograph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
