# Generated by Django 5.1.7 on 2025-03-29 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0002_remove_enrolment_class_title_remove_enrolment_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_title', models.CharField(max_length=100)),
                ('class_description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=12)),
                ('event_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_day', to='diary.eventday')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrol_status', to=settings.AUTH_USER_MODEL)),
                ('enrolled_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='details.eventclass')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventclass',
            constraint=models.UniqueConstraint(fields=('class_title',), name='unique_class_title_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('user', 'enrolled_class'), name='unique_user_enrolment'),
        ),
    ]
