# Generated by Django 5.1.7 on 2025-04-05 16:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_alter_eventclass_class_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventclass',
            name='class_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_class_image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='instructor_photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_instructor_image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
