# Generated by Django 5.1.7 on 2025-04-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_alter_eventclass_class_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventclass',
            old_name='instructor_photo',
            new_name='instructor_image',
        ),
    ]
