# Generated by Django 5.1.7 on 2025-04-06 13:43

from django.db import migrations, models


# Issue #112: CloudinaryField was replaced by ImageField, and the
# cloudinary package removed. Historical migrations only have to
# reproduce the schema, and CloudinaryField is a varchar(255), so
# CharField stands in for it exactly. Do not reintroduce the import.
class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_rename_instructor_photo_eventclass_instructor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventclass',
            name='class_image',
            field=models.CharField(blank=True, default='class_placeholder', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='instructor_image',
            field=models.CharField(blank=True, default='instructor_placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
