# Generated by Django 5.1.7 on 2025-04-12 15:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_alter_eventclass_class_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventclass',
            name='class_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='class_placeholder', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='instructor_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='instructor_placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
