# Generated by Django 5.2.1 on 2026-08-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_alter_eventclass_class_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventclass',
            name='class_image',
            field=models.ImageField(blank=True, null=True, upload_to='classes/'),
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='instructor_image',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/'),
        ),
    ]
