# Generated by Django 5.2.1 on 2026-08-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0012_cloudinary_ids_to_s3_keys'),
        ('diary', '0006_remove_eventday_unique_event_title_case_insensitive_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventclass',
            name='unique_class_title_case_insensitive',
        ),
        migrations.AddConstraint(
            model_name='eventclass',
            constraint=models.UniqueConstraint(fields=('event_day', 'start_time'), name='unique_class_start_time_per_day'),
        ),
    ]
